version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${PWD}/jenkins_home:/var/jenkins_home
      - ${PWD}/ssh:/home/jenkins/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
