version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    environment:
      - BROWSERSLIST_IGNORE_OLD_DATA=1
    volumes:
      - ~/.local/data/mongodb:/data/db
      - ~/mongodb:/mongodb
    ports:
      - 27017:27017
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    container_name: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
